
BASE_PATH: 'dataset/SEED/SEED_EEG/Preprocessed_EEG'

EPOCHS: 100
batch_size: 512 # 64, 256: Embedding
lr: 1e-4 # 1e-3, 2e-3
weight_decay: 1e-4
k_folds: 5

num_classes: 3
num_channels: 62
chunk_size: 200
overlap: 0

sampling_rate: 200 
num_subjects: 15
